### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by DTxCode** [aaron-ng/cs4500Assignment1#14]
Hey guys, it's a bit unclear what put() should be doing right now. 
Can I put something at any index? Or only if it's less than the (internal) capacity?

In other words, do we always grows to accommodate a put() call or is there ever a situation where we fail?

Also small note that ObjectArray() constructor still has an @param comment for size but no longer takes a parameter.

**Comment by aaron-ng** [comment]
My partner and I are currently discussing this right now. We will get back to you asap. We have fixed the documentation for the constructors.

**Comment by aaron-ng** [comment]
PR: https://github.com/aaron-ng/cs4500Assignment1/pull/23 We are just double checking the tests right now but this is the new implementation

**Comment by aaron-ng** [comment]
Merged PR: https://github.com/aaron-ng/cs4500Assignment1/pull/23 

Closing issue
