### ISSUE TITLE
Missing #includes in array.h

### ISSUE THREAD

**Issue by DTxCode** [aaron-ng/cs4500Assignment1#15]
I'm not sure whether the professors will test our code by pulling your exact spec file, but just in case, could you add these headers to your array.h?

```
#include <stdlib.h>
#include "object.h"
#include "string.h"
```

You have object.h, but the other two are needed (for size_t and String).

**Comment by aaron-ng** [comment]
Resolved in PR: https://github.com/aaron-ng/cs4500Assignment1/pull/20
