### ISSUE TITLE
nullptr for int, float, bool

### ISSUE THREAD

**Issue by evelynmawrey** [aaron-ng/cs4500Assignment1#17]
https://github.com/aaron-ng/cs4500Assignment1/blob/df8b7f850ad154fb69dadf0fd7e5b875ee6328ba/part2/src/array.h#L203

According to this comment, the values of int, float, and bool should be initialized to nullptr. This can't be done since a nullptr cannot be returned as an int, float, or bool from get(). Perhaps a valid alternative would be to initialize them to zero?

**Comment by aaron-ng** [comment]
This was leftover documentation when I added the extra classes. Fixed in PR: https://github.com/aaron-ng/cs4500Assignment1/pull/20
