### ISSUE TITLE
faulty tests?

### ISSUE THREAD

**Issue by evelynmawrey** [aaron-ng/cs4500Assignment1#18]
https://github.com/aaron-ng/cs4500Assignment1/blob/df8b7f850ad154fb69dadf0fd7e5b875ee6328ba/part2/tests/array_test.h#L192

Why should this test be false? Was this supposed to return false when you were able to supply a size in the constructor? Same for String, Int, Float, Bool.

https://github.com/aaron-ng/cs4500Assignment1/blob/df8b7f850ad154fb69dadf0fd7e5b875ee6328ba/part2/tests/array_test.h#L542

Why should the index be 4? Should it not be 0? Same for Bool.

**Comment by aaron-ng** [comment]
Fixed in this PR: https://github.com/aaron-ng/cs4500Assignment1/pull/21

**Comment by aaron-ng** [comment]
Actual fix here: https://github.com/aaron-ng/cs4500Assignment1/pull/22
