### ISSUE TITLE
String and Object classes

### ISSUE THREAD

**Issue by spar36** [aaron-ng/cs4500Assignment1#2]
Please update your string and object files to follow this post:
https://piazza.com/class/k51bluky59n2jr?cid=166

We need to get everyone to agree and it will make it easier for everyone if we all have the same specs for those type.

**Comment by spar36** [comment]
also https://piazza.com/class/k51bluky59n2jr?cid=330

**Comment by BlueSpud** [comment]
https://github.com/aaron-ng/cs4500Assignment1/pull/3
