### ISSUE TITLE
Extra imports

### ISSUE THREAD

**Issue by DTxCode** [aaron-ng/cs4500Assignment1#28]
Hey guys,

Could you remove these two includes from test-array.cpp?
```
#include "tests/object_test.h"
#include "tests/string_test.h"
```
We have different string/objects from you and it's clashing. Those two includes shouldn't be necessary to run the array tests.

Thanks 👍

**Comment by aaron-ng** [comment]
Resolved in latest PR: https://github.com/aaron-ng/cs4500Assignment1/pull/29

Closing issue.
