### ISSUE TITLE
Tests still using 'equal' method

### ISSUE THREAD

**Issue by ryanheminway** [aaron-ng/cs4500Assignment1#4]
From the recent PR, you guys updated the spec and some tests to use the 'equals' method instead of 'equal'. We appreciate this change, but some tests are still using the old 'equal' method. Please update this to be consistent with the spec. Thanks!

**Comment by ryanheminway** [comment]
Sorry, I missed the fact that the 'equal' method was still included in the Array classes. Is there a reason for this? We would appreciate if you could change it so it was 'equals', to be consistent with your Object class and tests. Let me know if there is a specific reason for this.

**Comment by aaron-ng** [comment]
Resolved in latest commit.
