### ISSUE TITLE
Array sub-types

### ISSUE THREAD

**Issue by DTxCode** [aaron-ng/cs4500Assignment1#5]
Hi guys, based on https://piazza.com/class/k51bluky59n2jr?cid=331 in order to support floats, bools, and ints in arrays, we'd like to ask you to create Array sub-classes for each (FloatArray, BoolArray, IntArray). 
Let us know if you agree with this, as Vitek seems to imply this is preferred to having wrappers around each of the primitives,

**Comment by spar36** [comment]
^^^ That was how I interpreted vitek as well. That is also what I have done for other groups.

**Comment by aaron-ng** [comment]
Added these new subclasses in this PR: https://github.com/aaron-ng/cs4500Assignment1/pull/9

Closing the issue.
